src/AdminBundle/Entity/AdminUser.php
<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
/**
 * AdminUser
 *
 * @ORM\Table(name="AdminUser")
 * @ORM\Entity(repositoryClass="AdminBundle\Repository\AdminUserRepository")
 */
class AdminUser implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=64)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=60, unique=true)
     */
    private $email;

    /**
     * @var bool
     *
     * @ORM\Column(name="isActive", type="boolean")
     */
    private $isActive = true;

    /**
     * @var string
     *
     * @ORM\Column(name="confirm_token", type="string", length=255, nullable=true)
     */
    private $confirmToken;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return AdminUser
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return AdminUser
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return AdminUser
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return AdminUser
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return string
     */
    public function getConfirmToken()
    {
        return $this->confirmToken;
    }

    /**
     * @param string $confirmToken
     */
    public function setConfirmToken($confirmToken)
    {
        $this->confirmToken = $confirmToken;
    }

    /**
     * Get isActive
     *
     * @return boolean
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function eraseCredentials()
    {
    }

    public function getRoles()
    {
        return array('ROLE_ADMIN');
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)

    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }

}

src/AdminBundle/Resources/views/partials/header.html.twig
<header class="header">
    <nav class="blue">
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

        <div class="nav-wrapper">
            <ul id="nav-mobile" class="right">
                <li>
                    <a href="{{ path('admin_logout') }}" data-target="chat-dropdown" style="display: flex" class="waves-effect">
                        Выйти<i class="material-icons">exit_to_app</i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

src/AdminBundle/Resources/views/partials/sidebar.html.twig
<aside id="slide-out" class="sidebar sidenav sidenav-fixed">
    <nav class="sidebar-nav blue">
        <ul id="dropdown2" class="dropdown-content">
            {% if app.user.roles[0] == 'ROLE_ADMIN' %}
                <li><a href="{{ path('admin_home') }}">Админ-панель</a></li>
            {% endif %}
            <li><a href="{{ path('app_homepage') }}" target="_blank">Сайт</a></li>
        </ul>
        <a class="dropdown-trigger" href="#" data-target="dropdown2" style="text-align: center; height: 100%">
            <img src="{{ asset('assets/images/logo.svg') }}" style="height: 80%; margin-top: 8px;">
        </a>
    </nav>
    <ul class="no-padding collapsible collapsible-accordion">
        <li class="bold waves-effect">
            <div class="collapsible-header white-text">
                    <span>
                        Тесты
                        <i class="material-icons white-text left">view_list</i>
                    </span>
                <i class="material-icons chevron white-text">chevron_left</i>
            </div>
            <div class="collapsible-body" >
                <ul>
                    <li><a href="{{ path('admin_quiz_index') }}" class="sidebar-link white-text">Все тесты<i class="material-icons white-text">description</i></a></li>
                    <li><a href="{{ path('admin_question_index') }}" class="sidebar-link white-text">Все вопросы<i class="material-icons white-text">help</i></a></li>
                    <li><a href="{{ path('admin_answer_index') }}" class="sidebar-link white-text">Все ответы<i class="material-icons white-text">question_answer</i></a></li>
                </ul>
            </div>
        </li>
    </ul>
</aside>